[CTRL-FLOW] Do CFI checking as the 4th pass (incomplete)
This doesn't work properly at the memont.  Basically, I use a function
called 'probe_register_function_instrs' that target exposes to
instrument all functions within the scope of the suspected system call
(sys_sendfile).  It works fine when I call it at the first time to
instrument all CALLs and RETs in sys_sendfile, which is the "root" of
our CFI checking.  However, when I call it again in the probe handler
triggered by the execution of a disassembed CALL, to recursively
instrument the "non-root" CALLs and RETs, I get an error message like
this:

  VERROR: probe_register_function_instrs:265: must supply a full
  function symbol!

It seems that the bsymbol I pass to the function is not valid.  I
simply do 'bsymbol = target_lookup_sym_addr(t, ip)' using the ip I got
from 'ip = target_read_reg(t, t->ipregno)', as David does in dump_target
to implement shadow stack.  Now, what's wrong?